approval_groups:
  - name: HEADS
    condition: 👤.*(\n^[\+|\-].*)|^[\+|\-].*👤
    check_type: pr_diff_body
    min_approvals: 1
    users:
    teams:
      - pr-custom-review-team
  - name: BAGS
    condition: 👜.*(\n^[\+|\-].*)|^[\+|\-].*👜
    check_type: pr_diff_body
    min_approvals: 1
    users:
      - sergejparity
    teams:
