approval_groups:
  - name: HEADS
    condition: 👤.*(\n^[\+|\-].*)|^[\+|\-].*👤
    check_type: pr_diff_body
    min_approvals: 1
    users:
    teams:
      - pr-custom-review-team
  - name: BAGS
    condition: '[👜.*(\n^[\+|\-].*)|^[\+|\-].*👜]'
    check_type: pr_diff_body
    min_approvals: 1
    users:
      - pr-custom-review-team
    teams:
  - name: runtime lib.rs
    condition: .*/runtime/.*lib.rs|.gitlab-ci.yml
    check_type: pr_files
    min_approvals: 2
    users:
    teams:
      - pr-custom-review-team