approval_groups:
  - name: HEADS
    condition: 👤.*(\n^[\+|\-].*)|^[\+|\-].*👤
    check_type: diff
    min_approvals: 1
    users:
    teams:
      - sergej-test
  - name: BAGS
    condition: (👜.*(\n^[\+|\-].*)|^[\+|\-].*👜)
    check_type: diff
    min_approvals: 1
    users:
      - sergioko737
      - sergioko747
      - sergioko757
    teams:
  - name: runtime lib.rs
    condition: .*/runtime/.*lib.rs
    check_type: changed_files
    min_approvals: 2
    users:
      - sergioko737
      - sergioko747
      - sergioko757
    teams:
      - sergej-test