name: PR Custom Review Status

on:
  pull_request:
    branches:
      - main
      - master
    types:
      - opened
      - reopened
      - synchronize
      - review_request_removed
  pull_request_review:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: pr-custom-review
        uses: joao-paulo-parity/pr-custom-review@tag
        with:
          token: ${{ secrets.GHA_TOKEN }}
          locks-review-team: pr-custom-review-team
          team-leads-team: jp
          action-review-team: pr-custom-review-team
