name: pr-custom-review

on:
  pull_request:
    branches:
      - main
      - master
    types:
      - opened
      - reopened
      - synchronize
      - review_request_removed
  pull_request_review:

jobs:
  assign_reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Generate App Auth Token
        id: get_token
        uses: microsoftgraph/get-app-token@5dc4e815ea2f976c51b11ea6f9e6310e06c55677
        with:
          application-id: ${{ secrets.PRCR_APP_ID }}
          application-private-key: ${{ secrets.PRCR_APP_PKEY }}
      - name: pr-custom-review
        uses: paritytech/pr-custom-review@v2
        with:
          token: ${{ steps.get_token.outputs.app-token }}
